kind: pipeline
type: docker
name: Build and Deploy

steps:
  - name: Build and Push to Docker Hub
    image: plugins/docker
    settings:
      repo: zeusxd/my-hello-app # Ganti 'zeusxd' jika username Docker Hub Anda berbeda
      tags:
        - latest
        - "${DRONE_BUILD_NUMBER}"
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      
  - name: Deploy to Kubernetes
    image: bitnami/kubectl:latest
    environment:
      KUBERNETES_SERVER:
        from_secret: kubernetes_server
      KUBERNETES_CERT:
        from_secret: kubernetes_cert
      KUBERNETES_TOKEN:
        from_secret: kubernetes_token
    commands:
      # Set up Kubeconfig for authentication
      - echo "$KUBERNETES_CERT" | base64 -d > /tmp/ca.crt
      - kubectl config set-cluster default --server="$KUBERNETES_SERVER" --certificate-authority=/tmp/ca.crt
      - kubectl config set-credentials default --token="$KUBERNETES_TOKEN"
      - kubectl config set-context default --cluster=default --user=default
      - kubectl config use-context default
      
      - |-
        sed -i "s|TAG_PLACEHOLDER|${DRONE_BUILD_NUMBER}|g" k8s-deployment.yaml
      
      # Terapkan manifest Kubernetes
      - kubectl apply -f k8s-deployment.yaml
      - echo "Deployment successful!"
