kind: pipeline
type: docker
name: Build and Deploy

steps:
  - name: Build and Push to Docker Hub
    image: plugins/docker
    settings:
      repo: zeusxd/my-hello-app # Ganti 'zeusxd' jika username Docker Hub Anda berbeda
      tags:
        - latest
        - "${DRONE_BUILD_NUMBER}"
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: Security Scan with Trivy
    image: aquasec/trivy:latest
    environment:
      TRIVY_USERNAME:
        from_secret: docker_username
      TRIVY_PASSWORD:
        from_secret: docker_password
    commands:
      - echo "Scanning image zeusxd/my-hello-app:${DRONE_BUILD_NUMBER}..."
      - trivy image --scanners vuln --timeout 30m --exit-code 1 --severity HIGH,CRITICAL --ignore-unfixed zeusxd/my-hello-app:${DRONE_BUILD_NUMBER}
    when:
      status: success
      
  - name: Deploy to Kubernetes
    image: bitnami/kubectl:latest
    environment:
      KUBERNETES_SERVER:
        from_secret: kubernetes_server
      KUBERNETES_CERT:
        from_secret: kubernetes_cert
      KUBERNETES_TOKEN:
        from_secret: kubernetes_token
    commands:
      # Set up Kubeconfig for authentication
      - echo "$KUBERNETES_CERT" | base64 -d > /tmp/ca.crt
      - kubectl config set-cluster default --server="$KUBERNETES_SERVER" --certificate-authority=/tmp/ca.crt
      - kubectl config set-credentials default --token="$KUBERNETES_TOKEN"
      - kubectl config set-context default --cluster=default --user=default
      - kubectl config use-context default
      
      # Ganti placeholder dan terapkan manifest dalam satu perintah
      - |-
        sed -e "s|TAG_PLACEHOLDER|${DRONE_BUILD_NUMBER}|g" -e "s|namespace: dev|namespace: dev-arif|g" k8s-deployment.yaml | kubectl apply -f -
    when:
      branch: [main]
      status: success

  - name: Deploy to Staging
    image: bitnami/kubectl:latest
    environment:
      KUBERNETES_SERVER:
        from_secret: kubernetes_server
      KUBERNETES_CERT:
        from_secret: kubernetes_cert
      KUBERNETES_TOKEN:
        from_secret: kubernetes_token
    commands:
      # Set up Kubeconfig for authentication
      - echo "$KUBERNETES_CERT" | base64 -d > /tmp/ca.crt
      - kubectl config set-cluster default --server="$KUBERNETES_SERVER" --certificate-authority=/tmp/ca.crt
      - kubectl config set-credentials default --token="$KUBERNETES_TOKEN"
      - kubectl config set-context default --cluster=default --user=default
      - kubectl config use-context default
      
      # Ganti placeholder tag dan namespace untuk staging
      - |-
        sed -e "s|TAG_PLACEHOLDER|${DRONE_BUILD_NUMBER}|g" -e "s|namespace: dev|namespace: staging-arif|g" -e "s|nodePort: 30080|nodePort: 30081|g" k8s-deployment.yaml | kubectl apply -f -
    when:
      branch: [staging]
      status: success
      trigger: manual
