apiVersion: v1
data:
  ca.crt: 
  namespace: ZGV2
  token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNkluWnFOR2RFUjFWNVYydGtXVWRMUkVOcVZuUjNZbEZUYkZkRE1FVjFjRk5uVVc4MlptTmlPVU5xT1hNaWZRLmV5SnBjM01pT
  2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUprWlhZaUxDSnJkV0ps
  Y201bGRHVnpMbWx2TDNObGNuWnBZMlZoWTJOdmRXNTBMM05sWTNKbGRDNXVZVzFsSWpvaVpISnZibVV0WkdWd2JHOTVaWEl0ZEc5clpXNGlMQ0pyZFdKbGNtNWxkR1Z6TG1sdkwzTmxjblpwWTJWaFkyTnZ
  kVzUwTDNObGNuWnBZMlV0WVdOamIzVnVkQzV1WVcxbElqb2laSEp2Ym1VdFpHVndiRzk1WlhJaUxDSnJkV0psY201bGRHVnpMbWx2TDNObGNuWnBZMlZoWTJOdmRXNTBMM05sY25acFkyVXRZV05qYjNWdWRDNT
  FhV1FpT2lJMll6TTFNRFF4WXkwME16UTVMVFJrTURndFlXVmpPQzFpWWpBMk5ETmlaR0UwWVdZaUxDSnpkV0lpT2lKemVYTjBaVzA2YzJWeWRtbGpaV0ZqWTI5MWJuUTZaR1YyT21SeWIyNWxMV1JsY0d4dmVXVnl
  JbjAuQi1jQWlEMDh6X1R1Mm1HQkJlNUo3Q0V2Y19VZTE2bTZMd0NxZW40WDFRWFFyZ0I5N2RMUWhYd0xMOC15MnVoZ0p6OUhDTmMzcV9KQThTRGI2OE5NSzBUVDJ4aVRNU0wzR18zS2Y4cmhCTURNV0RaWlg3Yy1VSHZXZ
  lBRLTFwUVlNdmpHbkpaNEcxUGhrU1NST0pBTzV1MUxDRkVRQVZFU254dGU1U3BQV1I3Z1pPQjlMaXhOUjJ6Z2NEZ3ZUOExZN0pOMEc1OVpscmxuNzlmb3EyaWFqTjMyQVdnZW9FRDBuMDNmU1Z5M0lvbUg2cndOV3UtNGdFa
  3hHTW5IdGlCbjN5aklFWDFscDVIOWJRcW5UNDFLVUdycDNxcks4T1owUVQxTzhlZ01FT001OGdzTjRWUXJCOUZuRFJUblVFRHdSV2F5N2lKSmlPeUNLSktLUEZoeHZR
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{"kubernetes.io/service-account.name":"drone-deployer"},"name":"drone-deployer-token","namespace":"dev"},"type":"kubernetes.io/service-account-token"}
    kubernetes.io/service-account.name: drone-deployer
    kubernetes.io/service-account.uid: 6c35041c-4349-4d08-aec8-bb0643bda4af
  creationTimestamp: "2025-11-30T12:29:24Z"
  name: drone-deployer-token
  namespace: dev
  resourceVersion: "108026"
  uid: 35f025e1-a131-4750-a008-b7aab46226f9
type: kubernetes.io/service-account-token
